##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-utils
    - gcc
    - git
    - intltool
    - itstool
    - libcanberra
    - libgtop
    - make
    - mate-common
    - mate-panel
    - python
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-utils
    - g++
    - git
    - gtk-doc-tools
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmate-panel-applet-dev
    - libx11-dev
    - libxext-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-xext-dev
    - xsltproc
    - yelp-tools
    - zlib1g-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-utils.git
    - desktop-file-utils
    - e2fsprogs-devel
    - gcc
    - gcc-c++
    - git
    - hardlink
    - libX11-devel
    - libXmu-devel
    - libcanberra-devel
    - libgtop2-devel
    - make
    - mate-common
    - mate-panel-devel
    - mesa-libGL-devel
    - popt-devel
    - redhat-rpm-config
    - usermode
    - yelp-tools

  ubuntu:
    - g++
    - git
    - gtk-doc-tools
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmate-panel-applet-dev
    - libx11-dev
    - libxext-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-xext-dev
    - xsltproc
    - yelp-tools
    - zlib1g-dev

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi
  # disable pt language for help in search tool
  - sed -i s/"IGNORE_HELP_LINGUAS ="/"IGNORE_HELP_LINGUAS = pt"/g gsearchtool/help/Makefile.am

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-utils-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
